name       : libsearpc
version    : '3.1'
release    : 4
source     :
    - https://github.com/haiwen/libsearpc/archive/v3.1-latest.tar.gz : e6b07e7c4ed9307f14bc4e470ed335df63e8f8fe1262a57ff5567ef218471403
license    : Apache-2.0
component  : programming
summary    : |
    A simple C language RPC framework (including both server side & client side)
description: |
    A simple C language RPC framework (including both server side & client side).
builddeps  :
    - pkgconfig(jansson)
    - python-gobject2
    - python-simplejson
rundeps    :
    - python-gobject2
    - python-simplejson
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
