name       : libsearpc
version    : '3.2'
release    : 5
source     :
    - https://github.com/haiwen/libsearpc/archive/v3.2-latest.tar.gz : 08411c2581e4c3967f4590f25a357952cd7d71d83229171a3c1e1f321d457806
license    : Apache-2.0
component  : programming
summary    : |
    A simple C language RPC framework (including both server side & client side)
description: |
    A simple C language RPC framework (including both server side & client side).
builddeps  :
    - pkgconfig(jansson)
    - python-gobject2
    - python-simplejson
rundeps    :
    - python-gobject2
    - python-simplejson
setup      : |
    %autogen --disable-static PYTHON=/usr/bin/python3
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
