name       : libsearpc
version    : 3.1
release    : 1
source     :
    - https://github.com/haiwen/libsearpc/archive/v3.1-latest.tar.gz : 13fddb5494f5367dc36c31afb7b7b868570225e37f6bb7a13ec6e323ef527eb2
license    : GPL-3.0
component  : programming
summary    : A simple C language RPC framework (including both server side & client side).
description: |
    A simple C language RPC framework (including both server side & client side).
builddeps  :
    - pkgconfig(jansson)
    - python-gobject2
    - python-simplejson
rundeps    :
    - python-gobject2
    - python-simplejson
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
