name       : libsearpc
version    : '3.2'
release    : 6
source     :
    - https://github.com/haiwen/libsearpc/archive/v3.2-latest.tar.gz : 6ebb4a46c3927f379ae6356a5de0f8f884d23a109530f7cc48ce5fffae5811c7
homepage   : https://www.seafile.com
license    : Apache-2.0
component  : programming
summary    : |
    A simple C language RPC framework (including both server side & client side)
description: |
    A simple C language RPC framework (including both server side & client side).
builddeps  :
    - pkgconfig(jansson)
    - python-simplejson
rundeps    :
    - python-simplejson
setup      : |
    %autogen --disable-static PYTHON=python3
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
