name       : libsearpc
version    : 3.2.0
release    : 8
source     :
    - https://github.com/haiwen/libsearpc/archive/refs/tags/v3.2.0.tar.gz : cd00197fcc40b45b1d5e892b2d08dfa5947f737e0d80f3ef26419334e75b0bff
homepage   : https://www.seafile.com
license    : Apache-2.0
component  : programming
summary    : |
    A simple C language RPC framework (including both server side & client side)
description: |
    A simple C language RPC framework (including both server side & client side).
builddeps  :
    - pkgconfig(jansson)
    - python-simplejson
rundeps    :
    - python-simplejson
setup      : |
    %autogen --disable-static PYTHON=python3
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
